[package]
name = "rgboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
int-enum = "1.1.1"
rand = "0.8.5"
sdl2 = { version = "0.36.0", features = ["bundled"] }
spin_sleep = "1.2.0"
